### ISSUE TITLE
Craiyon model doesn't seem to be open-source anymore

### ISSUE THREAD

**Issue by Adekiii** [Language-Technology-Assessment/main-database#26]
The [Craiyon model](https://www.craiyon.com/) (formerly [DALL·E Mini](https://huggingface.co/dalle-mini/dalle-mini)) makes no mention of being open-source anywhere, and no GitHub or Huggingface repository was found. Seems like they were [threatened with legal action](https://www.reddit.com/r/dalle2/comments/vgtgdc/openai_who_runs_dalle2_alleged_threatened_creator/) by OpenAI.

**Comment by liesenf** [comment]
checked internet archive and indeed no claims to open, OS are made. So removed from database
